# base configuration for all v6.x Arkadia Sensor Hub hardware.

substitutions:
  device_comment: SPECIFY_DEVICE_COMMENT_TO_BASELINE_YAML_INCLUDE

esp32:
  board: wemos_d1_mini32
  cpu_frequency: 240MHZ
  framework:
    type: esp-idf
    advanced:
      minimum_chip_revision: "3.1"

packages:
  diagnostics: !include 
    file: /workspace/include/diagnostics.yaml
  blinky: !include
    file: /workspace/include/interval-blinky.yaml
    vars:
      builtin_led_pin: "GPIO2"
  wired_ethernet: !include
    file: /workspace/include/wired-ethernet.yaml
    vars:
      ethernet_clk_pin: "GPIO18"  
      ethernet_mosi_pin: "GPIO23" 
      ethernet_miso_pin: "GPIO19" 
      ethernet_cs_pin: "GPIO05" 
      ethernet_interrupt_pin: "GPIO26" 
      ethernet_reset_pin: "GPIO4"
  tone_player: !include
    file: /workspace/include/rtttl-player.yaml
    vars:
      buzzer_pin: "GPIO33"
  ha_chime: !include
    file: /workspace/include/home-asst-tone-player.yaml
  radar_0: !include
    file: /workspace/include/HLK-LD2410-radar-motion.yaml
    vars:
      uart_id: "uart_1"
      radar_id: "ld2410_0"
      uart_tx_pin: "GPIO17" 
      uart_rx_pin: "GPIO16" 
  radar_1: !include
    file: /workspace/include/HLK-LD2410-radar-motion.yaml
    vars:
      uart_id: "uart_0"
      radar_id: "ld2410_1"
      uart_tx_pin: "GPIO1" 
      uart_rx_pin: "GPIO3" 
  i2c: !include
    file: /workspace/include/i2c.yaml
    vars:
      i2c_sda_pin: "GPIO21"
      i2c_scl_pin: "GPIO22"
      i2c_freq: "420kHz"

# the env sensor data needs to get updated to be something that remotely reads the data points from a given set of sensors in Home Assistant
# which are in turn updated by a separate MCU in the 6.0 iteration of the Arkadia House project.
  temp_humidity: !include
    file: /workspace/include/BMP280-AHT20-temp-humidity.yaml
    vars: 
      temperature_offset: "0"      
  illuminance: !include
    file: /workspace/include/photoresistor-illuminance.yaml
    vars:
      illuminance_pin: "GPIO39"

  display: !include
    file: /workspace/include/SDD1306-display-arkadia.yaml
  keypad: !include
    file: /workspace/include/10-key-keypad.yaml
  door_lock_0: !include 
    file: /workspace/include/door-lock.yaml
    vars: 
      door_lock_id: "door_lock_0"
      sensor_pin: "GPIO36"
      motor_pin_1: "GPIO32"
      motor_pin_2: "GPIO27"
  door_lock_1: !include 
    file: /workspace/include/door-lock.yaml
    vars: 
      door_lock_id: "door_lock_1"
      sensor_pin: "GPIO34"
      motor_pin_1: "GPIO15"
      motor_pin_2: "GPIO25"
  door_sensor_0: !include
    file: /workspace/include/door-sensor.yaml
    vars:
      door_sensor_id: "door_sensor_0"
      sensor_pin: "GPIO35"
  door_sensor_1: !include
    file: /workspace/include/door-sensor.yaml
    vars:
      door_sensor_id: "door_sensor_1"
      sensor_pin: "GPIO13"

<<: !include 
  file: /workspace/include/wemos-d1-mini-wired-baseline.yaml
  vars:
    # turn off UART0 logging so that we can use it for radar1
    logger_baud_rate: "0"
    device_friendly_name: "Arkadia House Sensor Hub v6 (${device_hostname})"
    device_comment: ${device_comment}
