# base configuration for all v6.x Arkadia Sensor Hub hardware.

substitutions:
  device_hostname: SPECIFY_HOSTNAME_WHEN_INCLUDING_BASELINE_YAML
  source_env_sensor_hostname: SPECIFY_ENV_SENSOR_HOSTNAME_FOR_DISPLAY_PACKAGE  

packages:
  diagnostics: !include 
    file: /workspace/include/diagnostics.yaml
    vars:
      builtin_led_pin: "GPIO2"
  standard_device: !include
    file: /workspace/include/standard-home-assistant-device.yaml
  wired_eth: !include
    file: /workspace/include/wired-ethernet.yaml
    vars:
      ethernet_clk_pin: "GPIO18"  
      ethernet_mosi_pin: "GPIO23" 
      ethernet_miso_pin: "GPIO19" 
      ethernet_cs_pin: "GPIO05" 
      ethernet_interrupt_pin: "GPIO26" 
      ethernet_reset_pin: "GPIO4"
  tone_player: !include
    file: /workspace/include/rtttl-player.yaml
    vars:
      buzzer_pin: "GPIO33"
  ha_chime: !include
    file: ./home-asst-chime-player.yaml
  radar_0: !include
    file: ./HLK-LD2410-radar-motion.yaml
    vars:
      uart_id: "uart_1"
      radar_id: "ld2410_0"
      uart_tx_pin: "GPIO17" 
      uart_rx_pin: "GPIO16" 
  radar_1: !include
    file: ./HLK-LD2410-radar-motion.yaml
    vars:
      uart_id: "uart_0"
      radar_id: "ld2410_1"
      uart_tx_pin: "GPIO1" 
      uart_rx_pin: "GPIO3" 
  i2c: !include
    file: /workspace/include/i2c.yaml
    vars:
      i2c_sda_pin: "GPIO21"
      i2c_scl_pin: "GPIO22"
      i2c_freq: "420kHz"
  display: !include
    file: ./SDD1306-display.yaml
    vars:
      # note the underscore replacing the hyphen; this is because Home Assistant converts
      # all device and entity names to snake case when creating the corresponding entity_id
      source_env_sensor_hostname: ${source_env_sensor_hostname}  
  keypad: !include
    file: ./10-key-keypad.yaml
  door_lock_0: !include 
    file: ./door-lock.yaml
    vars: 
      door_lock_id: "door_lock_0"
      sensor_pin: "GPIO36"
      motor_pin_1: "GPIO32"
      motor_pin_2: "GPIO27"
  door_lock_1: !include 
    file: ./door-lock.yaml
    vars: 
      door_lock_id: "door_lock_1"
      sensor_pin: "GPIO34"
      motor_pin_1: "GPIO15"
      motor_pin_2: "GPIO25"
  door_sensor_0: !include
    file: ./door-sensor.yaml
    vars:
      door_sensor_id: "door_sensor_0"
      sensor_pin: "GPIO35"
  door_sensor_1: !include
    file: ./door-sensor.yaml
    vars:
      door_sensor_id: "door_sensor_1"
      sensor_pin: "GPIO13"

esp32:
  # board: nodemcu-32s <-- This also works for the wemos d1 mini 
  board: wemos_d1_mini32
  cpu_frequency: 240MHZ
  toolchain: esp-idf   
  framework:
    type: esp-idf
    advanced:
      minimum_chip_revision: "3.1"
      sram1_as_iram: true
#      enable_ota_rollback: false

esphome:
  name: ${device_hostname}
  friendly_name: "Sensor Hub ${device_hostname[:3]}"
  comment: "Arkadia Sensor Hub Version 6.8"
  name_add_mac_suffix: false
  project:
    name: "ArkadiaHouse.SensorHub"
    version: "6.8"

logger:
  level: DEBUG
  # baud_rate = 0 will disable serial logging (API access to logs should still work, tho)
  # We set it to 0 so that we can use the UART0 pins for radar1
  baud_rate: 0
  logs:
    # turn the volume down on sensors as some are really noisy
    sensor: ERROR

        
