<<: !include 
  file: ./dmx-base.yaml
  vars:
    device_comment: "Arkadia House DMX controller on board 621. Controls lights DLxxx through DLyyy."

# uncomment this line to create single channel on/off lights for each DMX channel of both universes, which can be useful for testing and debugging.
#<<: !include ./dmx-debug-lights.yaml 

packages:
  light1: !include
    file: ./rgbww-lights-u1.yaml
  light2: !include
    file: ./rgbww-lights-u2.yaml
      