substitutions:
  device_hostname: 621-esphome
  device_comment: "Controls lights DLxxx through DLyyy."

<<: !include ./outputs-u1-001-155.yaml

# uncomment this line to create single channel on/off lights for each DMX channel of both universes, which can be useful for testing and debugging.
<<: !include ./debug-lights-u1.yaml 

# <<: !include
#   file: ./rgbww-lights-u1.00-04.yaml
#   vars:
#     light_prefix: ${device_hostname[:3]}

<<: !include ./dmx-base.yaml

