packages:
  outputs: !include 
    file: ./outputs-u1-001-155.yaml
  # this defines a single channel on/off light for each DMX channel of both universes, which can be useful for testing and debugging.
  debug-lights: !include
    file: ./debug-lights-u1.yaml
  base: !include
    file: ./dmx-base.yaml
    vars:
      device_hostname: 932-esphome



