# base configuration for all v1.x Arkadia wired DMX controller hardware.
# two DMX universes on the same device, with 2 RGBCW fixtures (10 channels) on each universe.

substitutions:
  device_hostname: SPECIFY_HOSTNAME_WHEN_INCLUDING_BASELINE_YAML
  device_comment: SPECIFY_COMMENT_WHEN_INCLUDING_BASELINE_YAML

external_components:
  - source: github://andyboeh/esphome-dmx512

packages:
  diagnostics: !include 
    file: /workspace/include/diagnostics.yaml
    vars:
      builtin_led_pin: "GPIO2"
  standard_device: !include
    file: /workspace/include/standard-home-assistant-device.yaml
  wired_eth: !include
    file: /workspace/include/wired-ethernet.yaml
    vars:
      ethernet_clk_pin: "GPIO18"  
      ethernet_mosi_pin: "GPIO23" 
      ethernet_miso_pin: "GPIO19" 
      ethernet_cs_pin: "GPIO05" 
      ethernet_interrupt_pin: "GPIO26" 
      ethernet_reset_pin: "GPIO4"

uart:
# Leaving use of UART0 commented out here in case I ever need to remember how to utilize all 3 UARTs on a single controller.

  # - id: uart_bus0
  #   baud_rate: 250000
  #   tx_pin: 
  #     number: GPIO27   
  #     allow_other_uses: true 
  #     inverted: false
  #   stop_bits: 2
  #   data_bits: 8
  #   parity: NONE

  - id: uart_bus1
    baud_rate: 250000
    tx_pin: 
      number: GPIO25   
      allow_other_uses: true 
      inverted: false
    stop_bits: 2
    data_bits: 8
    parity: NONE
  - id: uart_bus2
    baud_rate: 250000
    tx_pin: 
      number: GPIO17   
      allow_other_uses: true 
      inverted: false
    stop_bits: 2
    data_bits: 8
    parity: NONE

dmx512:
  # - id: dmx_u0   
  #   uart_id: uart_bus0
  #   tx_pin: 
  #     number: GPIO27
  #     allow_other_uses: true # For ESPHome >= 2023.12.0
  #   uart_num: 0
  #   force_full_frames: false
  #   periodic_update: true
  #   custom_break_len: 92 # 92=default optional
  #   custom_mab_len: 12 # 12=default optional
  #   update_interval: 500 # 500=default optional

  - id: dmx_u1  
    uart_id: uart_bus1
    tx_pin: 
      number: GPIO25
      allow_other_uses: true 
    uart_num: 1
    force_full_frames: false
    periodic_update: true
    custom_break_len: 92 # 92=default optional
    custom_mab_len: 12 # 12=default optional
    update_interval: 500 # 500=default optional
  - id: dmx_u2
    uart_id: uart_bus2
    tx_pin: 
      number: GPIO17
      allow_other_uses: true 
    uart_num: 2
    force_full_frames: false
    periodic_update: true


esp32:
  # board: nodemcu-32s <-- This also works for the wemos d1 mini 
  board: wemos_d1_mini32
  cpu_frequency: 240MHZ
  toolchain: esp-idf  
  framework:
    type: esp-idf
    advanced:
      minimum_chip_revision: "3.1"
      sram1_as_iram: true
#      enable_ota_rollback: false

esphome:
  name: ${device_hostname}
  friendly_name: "DMX Controller ${device_hostname[:3]}" 
  comment: ${device_comment}
  name_add_mac_suffix: false
  project:
    name: "ArkadiaHouse.DMXController"
    version: "1.2"

logger:
  level: DEBUG
  # baud_rate = 0 will disable serial logging (API access to logs should still work, tho)
  # we explicitly set the logger baud rate to 115200 so that UART0 is allocated, and our uart components start with 
  # UART1. If we ever wanted to have 3 UARTS on a single controller, we could use the logger for that by setting the
  # logger baud rate to 0.  Then uart initialization would start with UART0.
  baud_rate: 115200
  logs:
    # turn the volume down on sensors as some are really noisy
    sensor: ERROR
    dmx512: ERROR


