substitutions:
  device_hostname: SPECIFY_HOSTNAME_WHEN_INCLUDING_BASELINE_YAML
  device_friendly_name: "Baseline (${device_hostname})"
  device_comment: "Baseline for Lolin S2 Mini boards."
  logger_baud_rate: "115200"
  
esp32:
  board: lolin_s2_mini
  variant: ESP32S2
  cpu_frequency: 240MHZ
  toolchain: esp-idf  # or 'platformio' (default)  
  framework:
    type: esp-idf

<<: !include  
  file: /workspace/include/wifi.yaml

<<: !include 
  file: /workspace/include/esp32-device-baseline.yaml
  vars:
    device_friendly_name: ${device_hostname}
    device_comment: "Baseline for board."
    logger_baud_rate: "115200"
    builtin_led_pin: "GPIO15"
