sensor:
  - platform: adc
    # this needs to be an analog input pin
    pin: ${illuminance_pin}
    name: "Photoresistor 0"
    id: illuminance_id
    state_class: measurement
    device_class: illuminance
    accuracy_decimals: 0
    unit_of_measurement: lx
    attenuation: auto
    #raw: true
    update_interval: 10s
    filters:
      - multiply: 100
      - delta: 2.0
      # - clamp:
      #     min_value: 0
      #     max_value: 210
      #     ignore_out_of_range: true
      - calibrate_linear:
          method: exact
          datapoints:
          # sensor -> true value
          # percentages are from my light testbed setup.
            - 8.0 -> 0        # darkness
            - 86.4 -> 13.3    # 1%
            - 131 -> 55.0     # 10%
            - 173.8 -> 159.3  # 30%
            - 182.6 -> 265.3  # 40%
            - 189.6 -> 405.6  # 50%
