substitutions:
  logger_baud_rate: "115200"

packages:
  diagnostics: !include 
    file: /workspace/include/diagnostics.yaml
  blinky: !include
    file: /workspace/include/interval-blinky.yaml
    vars:
      builtin_led_pin: "GPIO2"
  wifi: !include  
    file: /workspace/include/wifi.yaml

# "All Device" baseline stuff here

<<: !include 
  file: /workspace/include/wemos-d1-mini-baseline.yaml
  vars:
    logger_baud_rate: ${logger_baud_rate}

