substitutions:
  device_hostname: SPECIFY_HOSTNAME_WHEN_INCLUDING_BASELINE_YAML
  device_friendly_name: "Baseline (${device_hostname})"
  device_comment: "Baseline for Wemos D1 Mini boards, with WiFi."
  logger_baud_rate: "115200"

<<: !include  
  file: /workspace/include/wifi.yaml

<<: !include 
  file: /workspace/include/wemos-d1-mini-baseline.yaml
  vars:
    device_hostname: ${device_hostname}
    device_friendly_name: ${device_friendly_name}
    device_comment: ${device_comment}
    logger_baud_rate: ${logger_baud_rate}

