substitutions:
  device_hostname: SPECIFY_HOSTNAME_WHEN_INCLUDING_BASELINE_YAML
  device_friendly_name: "Baseline (${device_hostname})"
  device_comment: "Baseline for Wemos D1 Mini boards, with Wired Ethernet."
  logger_baud_rate: "115200"

packages:
  diagnostics: !include 
    file: /workspace/include/diagnostics.yaml
  blinky: !include
    file: /workspace/include/interval-blinky.yaml
    vars:
      builtin_led_pin: "GPIO2"
  wired_ethernet: !include
    file: /workspace/include/wired-ethernet.yaml
    vars:
      ethernet_clk_pin: "GPIO18"  
      ethernet_mosi_pin: "GPIO23" 
      ethernet_miso_pin: "GPIO19" 
      ethernet_cs_pin: "GPIO05" 
      ethernet_interrupt_pin: "GPIO26" 
      ethernet_reset_pin: "GPIO4"

# "All Device" baseline stuff here

<<: !include 
  file: /workspace/include/wemos-d1-mini-baseline.yaml
  vars:
    device_hostname: ${device_hostname}
    device_friendly_name: ${device_friendly_name}
    device_comment: ${device_comment}
    logger_baud_rate: ${logger_baud_rate}

